Repository 6-SPOT/spot-be, pull requests merged in 2025-02, with the labels that each got.

#2 FEAT: 공통 응답 및 Error 반환 로직 완성
  build.gradle
  src/main/java/spot/spot/global/config/GlobalResponseHandler.java
  src/main/java/spot/spot/global/controller/HealthCheckController.java
  src/main/java/spot/spot/global/dto/response/ResultResponse.java
  src/main/java/spot/spot/global/exception/ErrorCode.java
  src/main/java/spot/spot/global/exception/GlobalException.java
  src/main/java/spot/spot/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: FEAT

#9 chore: Job Entity 설정 및 업로드
  .github/workflows/auto-assign.yml
  src/main/java/spot/spot/SpotApplication.java
  src/main/java/spot/spot/domain/job/entity/HashTag.java
  src/main/java/spot/spot/domain/job/entity/Job.java
  src/main/java/spot/spot/domain/member/OAuthProvider.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/review/entity/Review.java
  src/main/java/spot/spot/pay/entity/KlayAboutJob.java
  src/main/java/spot/spot/pay/entity/PayHistory.java
  src/main/java/spot/spot/pay/entity/Point.java
Labels: FEAT

#20 [FEAT] Jasypt 환경 구성 및 jasypt 이용 종료
  .gitignore
  build.gradle
  src/main/java/spot/spot/domain/chat/chatparticipant/entity/ChatParticipant.java
  src/main/java/spot/spot/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/spot/spot/domain/chat/message/entity/Message.java
  src/main/java/spot/spot/domain/chat/messagestatus/entity/MessageStatus.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/spot/spot/global/security/config/IssueEncryptString.java
  src/test/resources/application.yml
Labels: 최적화 ✔️, 환경 세팅 🌱

#27 chore: make Logging colorful
  build.gradle
  src/main/java/spot/spot/global/healthCheck/HealthCheckController.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: DOCS 📝, CHORE 🧹, 환경 세팅 🌱

#29 chore: MapStruct 환경 구성
  build.gradle
Labels: CHORE 🧹, 환경 세팅 🌱

#35 feat: 일 관련 부가 Entity 추가 및 연관 관계 작성 & MySQL 장착
  .gitignore
  build.gradle
  src/main/java/spot/spot/domain/job/entity/Certification.java
  src/main/java/spot/spot/domain/job/entity/Job.java
  src/main/java/spot/spot/domain/job/entity/Matching.java
  src/main/java/spot/spot/domain/job/repository/CertificationRepository.java
  src/main/java/spot/spot/domain/job/repository/HashTagRepository.java
  src/main/java/spot/spot/domain/job/repository/JobRepository.java
  src/main/java/spot/spot/domain/job/repository/MatchingRepository.java
  src/main/java/spot/spot/domain/member/entity/Ability.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/member/entity/Worker.java
  src/main/java/spot/spot/domain/member/entity/WorkerAbility.java
  src/main/java/spot/spot/domain/member/repository/AbilityRepository.java
  src/main/java/spot/spot/domain/member/repository/MemberRepository.java
  src/main/java/spot/spot/domain/member/repository/WorkerAbilityRepository.java
  src/main/java/spot/spot/domain/member/repository/WorkerRepository.java
  src/main/resources/application-db.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: FEAT 🛠️, 환경 세팅 🌱

#42 Chore/#22
  .gitignore
  build.gradle
  src/main/java/spot/spot/domain/chat/entity/ChatRoom.java
  src/main/java/spot/spot/global/ConstantUtil.java
  src/main/java/spot/spot/global/config/FeignClientConfig.java
  src/main/java/spot/spot/global/config/QuerydslConfig.java
  src/main/java/spot/spot/global/config/RedisConfig.java
  src/main/java/spot/spot/global/config/SwaggerConfig.java
  src/main/java/spot/spot/global/healthCheck/HealthCheckController.java
  src/main/java/spot/spot/global/logging/ColorLogger.java
  src/main/java/spot/spot/global/logging/LogConfig.java
  src/main/java/spot/spot/global/logging/Logging.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
  src/main/resources/application-db.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/spot/spot/global/config/RedisConfigTest.java
Labels: CHORE 🧹, FEAT 🛠️, 환경 세팅 🌱, 고도화 🆙

#44 chore: pay, payhistory, klayAboutJob 엔터티 수정
  src/main/java/spot/spot/domain/pay/entity/KlayAboutJob.java
  src/main/java/spot/spot/domain/pay/entity/PayHistory.java
  src/main/java/spot/spot/domain/pay/entity/Point.java
Labels: CHORE 🧹

#47 Feat/#45
  .gitignore
  build.gradle
  src/main/java/spot/spot/domain/job/entity/Job.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/member/entity/WorkDay.java
  src/main/java/spot/spot/domain/member/repository/MemberRepository.java
  src/main/java/spot/spot/domain/notification/controller/FcmController.java
  src/main/java/spot/spot/domain/notification/dto/request/FcmTestRequest.java
  src/main/java/spot/spot/domain/notification/dto/request/UpdateFcmTokenRequest.java
  src/main/java/spot/spot/domain/notification/dto/response/FcmDTO.java
  src/main/java/spot/spot/domain/notification/entity/FcmToken.java
  src/main/java/spot/spot/domain/notification/entity/NoticeType.java
  src/main/java/spot/spot/domain/notification/entity/Notification.java
  src/main/java/spot/spot/domain/notification/repository/FcmTokenRepository.java
  src/main/java/spot/spot/domain/notification/service/FcmService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
  src/main/java/spot/spot/global/auditing/config/JpaAuditingConfig.java
  src/main/java/spot/spot/global/auditing/entitiy/Created.java
  src/main/java/spot/spot/global/auditing/entitiy/CreatedAndDeleted.java
  src/main/java/spot/spot/global/auditing/entitiy/Deleted.java
  src/main/java/spot/spot/global/auditing/entitiy/Updated.java
  src/main/java/spot/spot/global/config/AsyncConfig.java
  src/main/java/spot/spot/global/config/FireBaseConfig.java
  src/main/java/spot/spot/global/config/SecurityConfig.java
  src/main/java/spot/spot/global/config/SwaggerConfig.java
  src/main/java/spot/spot/global/config/TestDataInitializerConfig.java
  src/main/java/spot/spot/global/security/util/UserAccessUtil.java
  src/main/java/spot/spot/global/util/ConstantUtil.java
  src/main/resources/application-h2.yml
  src/main/resources/application-mysql.yml
  src/main/resources/application.yml
Labels: FEAT 🛠️, API 구현 ✨, 환경 세팅 🌱

#59 feat: 카카오 간편 로그인 구현
  build.gradle
  src/main/java/spot/spot/domain/member/OAuthProvider.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/member/entity/OAuth2Member.java
  src/main/java/spot/spot/domain/member/entity/dto/MemberRequest.java
  src/main/java/spot/spot/domain/member/entity/dto/MemberRole.java
  src/main/java/spot/spot/domain/member/entity/dto/OAuth2MemberResponse.java
  src/main/java/spot/spot/domain/member/entity/jwt/JwtFilter.java
  src/main/java/spot/spot/domain/member/entity/jwt/JwtUtil.java
  src/main/java/spot/spot/domain/member/entity/jwt/Token.java
  src/main/java/spot/spot/domain/member/repository/MemberRepository.java
  src/main/java/spot/spot/domain/member/service/MemberService.java
  src/main/java/spot/spot/domain/member/service/OAuth2FailureHandler.java
  src/main/java/spot/spot/domain/member/service/OAuth2MemberService.java
  src/main/java/spot/spot/domain/member/service/OAuth2SuccessHandler.java
  src/main/java/spot/spot/domain/member/service/TokenService.java
  src/main/java/spot/spot/global/config/RedisConfig.java
  src/main/java/spot/spot/global/config/SecurityConfig.java
  src/main/java/spot/spot/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: FEAT 🛠️, API 구현 ✨, 외부 API 연동 🔗

#98 FEAT: 일 신청자 리스트 API 완성 + 해결사의 일 시작하기 API 완성
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
  src/main/java/spot/spot/domain/job/dto/request/JobRequest.java
  src/main/java/spot/spot/domain/job/dto/response/AttenderResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerReponse.java
  src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
  src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
  src/main/java/spot/spot/domain/job/repository/dsl/JobStatusQueryDsl.java
  src/main/java/spot/spot/domain/job/repository/dsl/WorkerSearchingQuerydsl.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/resources/application-local.yml
Labels: FEAT 🛠️, API 구현 ✨

#97 FEAT: 일 신청하기 API 완성
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
  src/main/java/spot/spot/domain/job/dto/request/Client2JobRequest.java
  src/main/java/spot/spot/domain/job/dto/request/Worker2JobRequest.java
  src/main/java/spot/spot/domain/job/dto/response/AttenderResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerAndErrorCodeResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerReponse.java
  src/main/java/spot/spot/domain/job/entity/Matching.java
  src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
  src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
  src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
  src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
  src/main/java/spot/spot/domain/job/repository/jpa/JobRepository.java
  src/main/java/spot/spot/domain/job/repository/jpa/MatchingRepository.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/domain/job/service/searching/JobSearchQueryDSLService.java
  src/main/java/spot/spot/domain/notification/repository/FcmTokenRepository.java
  src/main/java/spot/spot/domain/notification/service/FcmService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
  src/main/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApi.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/resources/application-local.yml
Labels: FEAT 🛠️, API 구현 ✨

#96 FEAT: 일 하나 상세 확인 API 완성
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
  src/main/java/spot/spot/domain/job/dto/request/Client2JobRequest.java
  src/main/java/spot/spot/domain/job/dto/request/Worker2JobRequest.java
  src/main/java/spot/spot/domain/job/dto/response/AttenderResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerAndErrorCodeResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerReponse.java
  src/main/java/spot/spot/domain/job/dto/response/NearByJobResponse.java
  src/main/java/spot/spot/domain/job/entity/Matching.java
  src/main/java/spot/spot/domain/job/entity/MatchingStatus.java
  src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
  src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
  src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
  src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
  src/main/java/spot/spot/domain/job/repository/jpa/JobRepository.java
  src/main/java/spot/spot/domain/job/repository/jpa/MatchingRepository.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/domain/job/service/searching/JobSearchQueryDSLService.java
  src/main/java/spot/spot/domain/notification/repository/FcmTokenRepository.java
  src/main/java/spot/spot/domain/notification/service/FcmService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
  src/main/java/spot/spot/global/klaytn/api/ExchangeRateByBithumbApi.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: FEAT 🛠️, API 구현 ✨

#104 REFACTOR: 일 신청하기 쿼리문 성능 최적화 및 모듈화
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerAndErrorCodeResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobWithOwnerReponse.java
  src/main/java/spot/spot/domain/job/entity/Matching.java
  src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
  src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
Labels: RESOLVED ❤️‍🩹🩹

#108 FEAT: 의뢰인이 마음에 드는 해결사에게 일을 의뢰하기 API + 의뢰할 시 해결사에게 FCM 알림 보내기
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/_docs/Job4WorkerDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/controller/Job4WorkerController.java
  src/main/java/spot/spot/domain/job/dto/request/Job4ClientRequest.java
  src/main/java/spot/spot/domain/job/dto/request/Job4WorkerRequest.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
Labels: FEAT 🛠️, API 구현 ✨

#109 FEAT: 의뢰자가 해결사의 요청 중 하나를 승낙하는 API 완성
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/dto/request/YesOrNoOfClientRequest.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/notification/service/FcmUtil.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
Labels: FEAT 🛠️, API 구현 ✨, RESOLVED ❤️‍🩹🩹

#119 FEAT: 노쇼한 해결사 일 철회 시키기 (의뢰자가 철회 요청 -> 10분 간 해결사에게서 아무 응답이 없으면 취소)
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/repository/dsl/ChangeJobStatusDsl.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/domain/job/service/JobUtil.java
  src/main/java/spot/spot/global/config/TestDataInitializerConfig.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/scheduler/SchedulingConfig.java
  src/main/java/spot/spot/global/scheduler/SchedulingTask.java
Labels: FEAT 🛠️, API 구현 ✨

#131 RESOLVED: Security 레벨 에러들이 계속 정상 응답에 담기는 오류 해결
  src/main/java/spot/spot/domain/member/controller/MemberController.java
  src/main/java/spot/spot/domain/member/service/MemberService.java
  src/main/java/spot/spot/domain/member/service/TokenService.java
  src/main/java/spot/spot/global/redis/config/RedisConfig.java
  src/main/java/spot/spot/global/redis/entity/Token.java
  src/main/java/spot/spot/global/redis/service/TokenService.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/response/format/FilterResponse.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
  src/main/java/spot/spot/global/response/handler/ResponseStatusSetter.java
  src/main/java/spot/spot/global/security/config/SecurityConfig.java
  src/main/java/spot/spot/global/security/filter/CustomAccessDeninedHandler.java
  src/main/java/spot/spot/global/security/filter/CustomAuthenticationEntryPoint.java
  src/main/java/spot/spot/global/security/filter/JwtFilter.java
  src/main/java/spot/spot/global/security/filter/OAuth2FailureHandler.java
  src/main/java/spot/spot/global/security/filter/OAuth2SuccessHandler.java
  src/main/java/spot/spot/global/security/util/JwtUtil.java
  src/main/java/spot/spot/global/security/util/jwt/JwtFilter.java
  src/main/java/spot/spot/global/security/util/jwt/JwtUtil.java
  src/main/java/spot/spot/global/stomp/StompEventListener.java
  src/main/java/spot/spot/global/stomp/StompHandler.java
  src/main/java/spot/spot/global/stomp/StompWebSocketConfig.java
  src/main/java/spot/spot/global/util/ConstantUtil.java
Labels: BUG 👾, RESOLVED ❤️‍🩹🩹
