Repository 6-SPOT/spot-be, pull requests merged in 2025-03, with the labels that each got.

#138 FEAT: 내가 맡긴 일 현황 한 눈에 보기 API 완성
  src/main/java/spot/spot/domain/job/_docs/Job4ClientDocs.java
  src/main/java/spot/spot/domain/job/controller/Job4ClientController.java
  src/main/java/spot/spot/domain/job/dto/response/JobResponse.java
  src/main/java/spot/spot/domain/job/dto/response/JobSituationResponse.java
  src/main/java/spot/spot/domain/job/mapper/Job4ClientMapper.java
  src/main/java/spot/spot/domain/job/mapper/Job4WorkerMapper.java
  src/main/java/spot/spot/domain/job/repository/dsl/SearchingListDsl.java
  src/main/java/spot/spot/domain/job/service/Job4ClientService.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
Labels: FEAT 🛠️, API 구현 ✨

#143 FEAT: 실시간 확인 SOCKET 완성
  src/main/java/spot/spot/domain/job/controller/JobStreamingController.java
  src/main/java/spot/spot/domain/job/dto/request/PositionRequest.java
  src/main/java/spot/spot/domain/job/dto/response/PositionResponse.java
  src/main/java/spot/spot/domain/job/mapper/JobStreamingMapper.java
  src/main/java/spot/spot/domain/job/service/JobStreamingService.java
  src/main/java/spot/spot/domain/member/controller/MemberController.java
  src/main/java/spot/spot/domain/member/dto/response/TokenResponse.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/java/spot/spot/global/stomp/ActiveSessionTracker.java
  src/main/java/spot/spot/global/stomp/StompEventListener.java
  src/main/java/spot/spot/global/stomp/StompHandler.java
  src/main/java/spot/spot/global/stomp/StompUtil.java
  src/main/java/spot/spot/global/stomp/StompWebSocketConfig.java
  src/main/java/spot/spot/global/util/ConstantUtil.java
Labels: FEAT 🛠️, API 구현 ✨

#137 refactor: payService, pointService 1차 리팩토링
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/member/service/MemberService.java
  src/main/java/spot/spot/domain/pay/controller/PayController.java
  src/main/java/spot/spot/domain/pay/controller/PointController.java
  src/main/java/spot/spot/domain/pay/entity/KlayAboutJob.java
  src/main/java/spot/spot/domain/pay/entity/PayHistory.java
  src/main/java/spot/spot/domain/pay/entity/Point.java
  src/main/java/spot/spot/domain/pay/entity/dto/request/PayApproveRequestDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/request/PointServeRequestDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayApproveResponse.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayApproveResponseDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayCancelResponse.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayCancelResponseDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayOrderResponse.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayOrderResponseDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayReadyResponse.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayReadyResponseDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PaySuccessResponseDto.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PointServeResponseDto.java
  src/main/java/spot/spot/domain/pay/service/PayService.java
  src/main/java/spot/spot/domain/pay/service/PointService.java
  src/main/java/spot/spot/global/response/format/ErrorCode.java
  src/main/java/spot/spot/global/response/handler/GlobalExceptionHandler.java
  src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
  src/test/java/spot/spot/domain/pay/controller/PayControllerExceptionTest.java
  src/test/java/spot/spot/domain/pay/controller/PayControllerTest.java
  src/test/java/spot/spot/domain/pay/controller/PointControllerExceptionTest.java
  src/test/java/spot/spot/domain/pay/controller/PointControllerTest.java
  src/test/java/spot/spot/domain/pay/repository/KlayAboutJobRepositoryTest.java
  src/test/java/spot/spot/domain/pay/repository/PayQueryRepositoryTest.java
  src/test/java/spot/spot/domain/pay/repository/PointRepositoryTest.java
  src/test/java/spot/spot/domain/pay/service/PayServiceExceptionTest.java
  src/test/java/spot/spot/domain/pay/service/PayServiceTest.java
  src/test/java/spot/spot/domain/pay/service/PointServiceExceptionTest.java
  src/test/java/spot/spot/domain/pay/service/PointServiceTest.java
Labels: TEST🔬, REFACTORING 🛠

#160 fix: payReadyResponseDto payHistory 필드 삭제
  src/main/java/spot/spot/domain/pay/entity/PayHistory.java
  src/main/java/spot/spot/domain/pay/entity/dto/response/PayReadyResponseDto.java
  src/main/java/spot/spot/domain/pay/service/PayService.java
Labels: BUG 👾, RESOLVED ❤️‍🩹🩹

#166 FIX: 자신이 신청한 일인지 아닌지 같이 넣기
  src/main/java/spot/spot/domain/job/dto/response/JobDetailResponse.java
  src/main/java/spot/spot/domain/job/repository/dsl/MatchingDsl.java
  src/main/java/spot/spot/domain/job/service/Job4WorkerService.java
  src/main/java/spot/spot/global/response/handler/GlobalResponseHandler.java
Labels: API 구현 ✨, FIX 👨‍🔧

#170 refactor: 포인트 등록 동시성 락 문제
  src/main/java/spot/spot/domain/member/repository/MemberRepository.java
  src/main/java/spot/spot/domain/pay/controller/PayController.java
  src/main/java/spot/spot/domain/pay/repository/PointRepository.java
  src/main/java/spot/spot/domain/pay/service/PointService.java
  src/test/java/spot/spot/domain/pay/service/PointServiceExceptionTest.java
  src/test/java/spot/spot/domain/pay/service/PointServiceTest.java
Labels: TEST🔬, REFACTORING 🛠, RESOLVED ❤️‍🩹🩹, FIX 👨‍🔧

#182 FIX: 일 현황에 아무도 신청 안한 일도 올라 오도록 추가 isOwner(일의 주인 인가) 추가
  src/main/java/spot/spot/domain/job/command/dto/response/JobSituationResponse.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
Labels: FIX 👨‍🔧

#191 REFACTOR: Notification domain CQS 패턴 적용 및 SWAGGER 명세 분리
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
  src/main/java/spot/spot/domain/job/command/service/_docs/ClientCommandServiceDocs.java
  src/main/java/spot/spot/domain/job/command/service/_docs/WorkerCommandServiceDocs.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
  src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
  src/main/java/spot/spot/domain/job/v1/query/controller/WorkerQueryVersion1Controller.java
  src/main/java/spot/spot/domain/job/v1/query/controller/_docs/WorkerQueryVersion1Docs.java
  src/main/java/spot/spot/domain/job/v1/query/service/WorkerQueryVersion1Service.java
  src/main/java/spot/spot/domain/member/_docs/MemberDocs.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/domain/notification/command/controller/NotificationCommandController.java
  src/main/java/spot/spot/domain/notification/command/controller/_docs/NotificationCommandDocs.java
  src/main/java/spot/spot/domain/notification/command/dto/request/FcmTestRequest.java
  src/main/java/spot/spot/domain/notification/command/dto/request/UpdateFcmTokenRequest.java
  src/main/java/spot/spot/domain/notification/command/dto/response/FcmDTO.java
  src/main/java/spot/spot/domain/notification/command/entity/FcmToken.java
  src/main/java/spot/spot/domain/notification/command/entity/NoticeType.java
  src/main/java/spot/spot/domain/notification/command/entity/Notification.java
  src/main/java/spot/spot/domain/notification/command/repository/FcmTokenRepository.java
  src/main/java/spot/spot/domain/notification/command/service/FcmService.java
  src/main/java/spot/spot/domain/notification/command/service/FcmUtil.java
  src/main/java/spot/spot/global/config/SwaggerConfig.java
  src/main/java/spot/spot/global/healthCheck/HealthCheckController.java
  src/main/java/spot/spot/global/healthcheck/command/controller/HealthCheckCommandController.java
  src/main/java/spot/spot/global/healthcheck/command/controller/_docs/HealthCheckCommandDocs.java
  src/main/java/spot/spot/global/healthcheck/command/dto/SampleDto.java
  src/main/java/spot/spot/global/healthcheck/query/controller/HealthCheckQueryController.java
  src/main/java/spot/spot/global/healthcheck/query/controller/_docs/HealthCheckQueryDocs.java
  src/test/java/spot/spot/domain/job/controller/Job4ClientControllerTest.java
Labels: REFACTORING 🛠

#200 FIX: 근처 일 찾기 api (/api/job/worker/search) default 값 안 나가는 오류 수정
  src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
  src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
Labels: FIX 👨‍🔧

#206 FEAT: 해결사의 인증 사진 리스트 조회 API 완성
  src/main/java/spot/spot/domain/job/command/repository/jpa/CertificationRepository.java
  src/main/java/spot/spot/domain/job/query/controller/ClientQueryController.java
  src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
  src/main/java/spot/spot/domain/job/query/controller/_docs/ClientQueryDocs.java
  src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java
  src/main/java/spot/spot/domain/job/query/dto/response/AttenderResponse.java
  src/main/java/spot/spot/domain/job/query/dto/response/CertificationImgResponse.java
  src/main/java/spot/spot/domain/job/query/mapper/ClientQueryMapper.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java
  src/main/java/spot/spot/domain/job/query/service/ClientQueryService.java
  src/main/java/spot/spot/domain/job/query/service/PositionQueryService.java
  src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
  src/main/java/spot/spot/domain/job/query/service/_docs/ClientQueryServiceDocs.java
  src/main/java/spot/spot/domain/job/query/service/_docs/PositionQueryServiceDocs.java
  src/main/java/spot/spot/domain/job/query/service/_docs/WorkerQueryServiceDocs.java
  src/main/resources/application-test.yml
Labels: FEAT 🛠️, API 구현 ✨

#209 FEAT: 채팅방 알림 리스트 API 구현
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
  src/main/java/spot/spot/domain/notification/command/repository/NotificationRepository.java
  src/main/java/spot/spot/domain/notification/command/service/FcmAsyncSendingUtil.java
  src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
  src/main/java/spot/spot/domain/notification/command/service/FcmService.java
  src/main/java/spot/spot/domain/notification/query/controller/NotificationQueryController.java
  src/main/java/spot/spot/domain/notification/query/controller/_docs/NotificationQueryControllerDocs.java
  src/main/java/spot/spot/domain/notification/query/dto/response/NotificationResponse.java
  src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
  src/main/java/spot/spot/domain/notification/query/service/NotificationService.java
Labels: FEAT 🛠️, API 구현 ✨

#211 FIX: workerId 없이 jobId로만 원하는 값 가져오기 로직 구현 완료
  src/main/java/spot/spot/domain/job/query/controller/WorkerQueryController.java
  src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java
  src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
  src/main/java/spot/spot/domain/job/query/service/_docs/WorkerQueryServiceDocs.java
Labels: RESOLVED ❤️‍🩹🩹, FIX 👨‍🔧

#215 FIX: 확정 혹은 거절 에서 WorkerId 제외
  build.gradle
  src/main/java/spot/spot/domain/job/command/controller/ClientCommandController.java
  src/main/java/spot/spot/domain/job/command/controller/_docs/ClientCommandDocs.java
  src/main/java/spot/spot/domain/job/command/dto/request/ConfirmOrRejectRequest.java
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/_docs/ClientCommandServiceDocs.java
  src/main/java/spot/spot/domain/member/repository/MemberQueryRepository.java
Labels: FIX 👨‍🔧

#218 FIX: NOTIFICATION 알림 리스트 Type-case 오류 해결
  src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
Labels: FIX 👨‍🔧

#219 CHORE: V1 버전 API 컨트롤러 서비스 모두 v1 폴더로 이동
  src/main/java/spot/spot/domain/job/command/controller/ClientCommandController.java
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/v1/command/controller/ClientCommandVersion1Controller.java
  src/main/java/spot/spot/domain/job/v1/command/controller/_docs/ClientCommandVersion1Docs.java
  src/main/java/spot/spot/domain/job/v1/command/service/ClientCommandVersion1Service.java
  src/main/java/spot/spot/domain/job/v1/query/controller/_docs/WorkerQueryVersion1Docs.java
  src/main/java/spot/spot/global/healthcheck/command/controller/_docs/HealthCheckCommandDocs.java
  src/main/java/spot/spot/global/healthcheck/query/controller/_docs/HealthCheckQueryDocs.java
Labels: CHORE 🧹

#223 FEAT: DB 최신화 (단순 위도 경도 저장 -> mySQL POINT (공간 객체 - 세계적으로 GPS에 활용됨) 로 변환 및 관련 일 등록, 구직자 등록 로직 개선
  build.gradle
  src/main/java/spot/spot/domain/job/command/entity/Job.java
  src/main/java/spot/spot/domain/job/command/entity/Matching.java
  src/main/java/spot/spot/domain/job/command/mapper/ClientCommandMapper.java
  src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
  src/main/java/spot/spot/domain/job/command/repository/dsl/WorkerUpdatingCommandDsl.java
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
  src/main/java/spot/spot/domain/member/entity/Member.java
  src/main/java/spot/spot/global/config/GeometryFactoryConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
Labels: ADVANCEMENT 🆙, FIX 👨‍🔧

#224 FEAT: mySQL 방언, 공간 데이터 활용 없이 순수 쿼리 최적화
  src/main/java/spot/spot/domain/job/query/controller/_docs/WorkerQueryDocs.java
  src/main/java/spot/spot/domain/job/query/dto/response/NearByJobResponse.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/SearchingListQueryDsl.java
  src/main/java/spot/spot/domain/job/query/repository/dsl/_docs/SearchingListQueryDocs.java
  src/main/java/spot/spot/domain/job/query/repository/jpa/JobRepository.java
  src/main/java/spot/spot/domain/job/query/service/WorkerQueryService.java
  src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobJPQLQueryUtil.java
  src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobNativeQueryUtil.java
  src/main/java/spot/spot/domain/job/query/util/searching/SearchingJobQueryDSLUtil.java
  src/main/java/spot/spot/domain/job/v1/query/controller/WorkerQueryControllerV1.java
  src/main/java/spot/spot/domain/job/v1/query/controller/_docs/WorkerQueryDocsV1.java
  src/main/java/spot/spot/domain/job/v1/query/mapper/WorkerQueryMapperV1.java
  src/main/java/spot/spot/domain/job/v1/query/repository/dsl/SearchingListQueryDslV1.java
  src/main/java/spot/spot/domain/job/v1/query/repository/jpa/JobRepositoryV1.java
  src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobJpqlQueryUtilVV1.java
  src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobNativeQueryUtilVV1.java
  src/main/java/spot/spot/domain/job/v1/query/service/SearchingJobQueryDslVersionUtilVV1.java
  src/main/java/spot/spot/domain/job/v1/query/service/WorkerQueryServiceV1.java
  src/main/java/spot/spot/domain/job/v1/query/service/_docs/SearchingJobQueryVersionUtilV1.java
Labels: DOCS 📝, ADVANCEMENT 🆙

#233 FIX: FCM 양방향 송수신 설정 및 알림 저장 로직, 전 매칭 생애주기에 구현
  src/main/java/spot/spot/domain/job/command/controller/WorkerCommandController.java
  src/main/java/spot/spot/domain/job/command/dto/response/RegisterJobResponse.java
  src/main/java/spot/spot/domain/job/command/mapper/ClientCommandMapper.java
  src/main/java/spot/spot/domain/job/command/mapper/NotificationMapper.java
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
  src/main/java/spot/spot/domain/job/command/service/_docs/WorkerCommandServiceDocs.java
  src/main/java/spot/spot/domain/job/v1/command/service/ClientCommandVersion1Service.java
  src/main/java/spot/spot/domain/notification/command/dto/response/FcmDTO.java
  src/main/java/spot/spot/domain/notification/command/service/FcmMessageUtil.java
Labels: FIX 👨‍🔧

#235 HOT FIX: Notification 철자 에러 수정
  src/main/java/spot/spot/domain/job/command/mapper/NotificationMapper.java
  src/main/java/spot/spot/domain/job/command/mapper/WorkerCommandMapper.java
  src/main/java/spot/spot/domain/notification/command/entity/Notification.java
  src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
Labels: HOT FIX 🔥, FIX 👨‍🔧

#245 FIX: NOTIFICATION ERROR 해결
  src/main/java/spot/spot/domain/notification/query/dto/response/NotificationResponse.java
  src/main/java/spot/spot/domain/notification/query/repository/SearchingNotificationListDsl.java
Labels: RESOLVED ❤️‍🩹🩹, FIX 👨‍🔧

#246 FEAT: 리뷰 LIST API 완성 및 페이지 네이션 적용 완료
  src/main/java/spot/spot/domain/review/controller/ReviewController.java
  src/main/java/spot/spot/domain/review/controller/_docs/ReviewDocs.java
  src/main/java/spot/spot/domain/review/dto/response/AuthoredReview.java
  src/main/java/spot/spot/domain/review/dto/response/ReceivedReview.java
  src/main/java/spot/spot/domain/review/repository/ReviewRepository.java
  src/main/java/spot/spot/domain/review/repository/searchingReivewListDsl.java
  src/main/java/spot/spot/domain/review/service/ReviewService.java
Labels: FEAT 🛠️

#251 CHORE: TOKEN 수명 7일로 늘리기
  src/main/java/spot/spot/domain/member/_docs/MemberDocs.java
  src/main/resources/application.yml
Labels: CHORE 🧹

#258 FIX: 일 등록 시 사진 없어도 되도록 수정 (for Test)
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
Labels: OPTIMIZATION ✔️

#259 FIX: 일 완료 버튼 안되는 것 수정
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
Labels: FIX 👨‍🔧

#260 FIX: PAY 강결합 주석 처리
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
Labels: FIX 👨‍🔧

#263 CHORE: 필요 없는 yml 지우기
  .github/workflows/auto-assign.yml
  .github/workflows/dev-test-actions.yml
Labels: CHORE 🧹

#264 CHORE: max- connection-pool size 늘리기
  src/main/resources/application-test.yml
Labels: CHORE 🧹

#266 FEAT: Thread 거절에 대한 재시도 로직 에서 지연 변이 로직 추가
  src/main/java/spot/spot/domain/job/command/service/ClientCommandService.java
  src/main/java/spot/spot/domain/job/command/service/WorkerCommandService.java
  src/main/java/spot/spot/domain/notification/command/service/FcmAsyncSendingUtil.java
  src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java
  src/main/java/spot/spot/global/retry/RetryConfig.java
Labels: OPTIMIZATION ✔️, ADVANCEMENT 🆙

#267 FEAT: ASYNC 대기 큐 값 늘리기
  src/main/java/spot/spot/global/config/AsyncConfig.java
  src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java
Labels: TEST🔬

#269 FEAT: ASYNC 대기 큐 다시 되돌리기
  src/main/java/spot/spot/global/config/AsyncConfig.java
  src/main/java/spot/spot/global/retry/ExponentialJitterBackOffPolicy.java
Labels: FIX 👨‍🔧
